language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: L/xZLshc8ifvsC45F9ssIr6q8tFHaHD5K2vHal+lxwuaqTQu7HIPdPXubILhb7eqRaNZp3XcfLIw1GurIblTAwN3wGlYlO5zhLicPheL2ObbSstapU7n+KFXbhbll306kdA8RrAxzjh7TaDVgDbqd3ZghMgt8vyo7GZoI/GDJ1eR2k0bk7nle1hyHLZ5HfhnUdiV3ecPa6x5W/rg8uZS88w09BInR9HZnX4fSacedJTucZgBGhW62xcP1TLPT5guoMCTEtN6okaI3WR7bZGWIS136F6WioFpq2WRxbcmm+D9zcyIHR9qLgV8QCJNPu8k989Kc7tYwVcW5KnKA8pbjxyBIrkfEv3PJAEzcdybqeHF3osEu55QE1c8bnEL9Vmab5FxOSypaVk9SUae4mV7f7jlsl56VkpjwLq/8PE2WL4xLVAUTS0ZSbYdfHyB+2g4z9JL8vUen85nFiG2bKQ1zqk2Fj8wjg5agqGEWum805Mk09CvpkmJa+zDw7VQVqnOhZYx0vB+4ie2l7J+B93CbPRznh353TxIqw94XPUKrER1Y6eiPt92eKcjXkocxWgEFcb6aDqDxwASN+MWbmqSjobhAQMdIoUsfsvPE20/tO0V6WMucrEdcYn6Lh26/DjYqmF4JX3jAce5/qO4bgNjzdI97nFjP6FFKOXSD/ITzXA=
  app: calm-lowlands-97439
  on:
    repo: True14/blog-tests-naeem-jonathan
